# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-02-05 12:39
from __future__ import unicode_literals

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('degree_name', models.CharField(max_length=255)),
                ('degree_branch', models.CharField(max_length=255)),
                ('degree_year', models.IntegerField(choices=[(1847, 1847), (1848, 1848), (1849, 1849), (1850, 1850), (1851, 1851), (1852, 1852), (1853, 1853), (1854, 1854), (1855, 1855), (1856, 1856), (1857, 1857), (1858, 1858), (1859, 1859), (1860, 1860), (1861, 1861), (1862, 1862), (1863, 1863), (1864, 1864), (1865, 1865), (1866, 1866), (1867, 1867), (1868, 1868), (1869, 1869), (1870, 1870), (1871, 1871), (1872, 1872), (1873, 1873), (1874, 1874), (1875, 1875), (1876, 1876), (1877, 1877), (1878, 1878), (1879, 1879), (1880, 1880), (1881, 1881), (1882, 1882), (1883, 1883), (1884, 1884), (1885, 1885), (1886, 1886), (1887, 1887), (1888, 1888), (1889, 1889), (1890, 1890), (1891, 1891), (1892, 1892), (1893, 1893), (1894, 1894), (1895, 1895), (1896, 1896), (1897, 1897), (1898, 1898), (1899, 1899), (1900, 1900), (1901, 1901), (1902, 1902), (1903, 1903), (1904, 1904), (1905, 1905), (1906, 1906), (1907, 1907), (1908, 1908), (1909, 1909), (1910, 1910), (1911, 1911), (1912, 1912), (1913, 1913), (1914, 1914), (1915, 1915), (1916, 1916), (1917, 1917), (1918, 1918), (1919, 1919), (1920, 1920), (1921, 1921), (1922, 1922), (1923, 1923), (1924, 1924), (1925, 1925), (1926, 1926), (1927, 1927), (1928, 1928), (1929, 1929), (1930, 1930), (1931, 1931), (1932, 1932), (1933, 1933), (1934, 1934), (1935, 1935), (1936, 1936), (1937, 1937), (1938, 1938), (1939, 1939), (1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)])),
                ('present_desig', models.CharField(max_length=255)),
                ('present_dept', models.CharField(max_length=255)),
                ('present_office', models.TextField()),
                ('present_residence', models.TextField()),
                ('delivery_address', models.TextField()),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address_for_correspondence', models.CharField(choices=[('Office Address', 'Office Address'), ('Residence Address', 'Residence Address')], max_length=50)),
                ('photo', models.ImageField(upload_to='website/media/alumnicard/photo/')),
                ('photo_sign', models.ImageField(upload_to='website/media/alumnicard/sign/')),
                ('photo_degree', models.ImageField(upload_to='website/media/alumnicard/degree/')),
            ],
        ),
        migrations.CreateModel(
            name='DistinguishedAlumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('diploma', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('category', models.CharField(choices=[('AR', 'Academic Research'), ('CE', 'Corporate Development/Adminstration/Entrepreneurship'), ('SA', 'Social Sciences/Engineering and Services/Public Adminstration'), ('SS', 'Service to Society')], max_length=50)),
                ('description', models.TextField()),
                ('contribution', models.TextField()),
                ('photo', models.ImageField(upload_to='website/media/distinguisted/images/')),
                ('resume', models.FileField(upload_to='website/media/distinguisted/resumes/')),
                ('optional1', models.FileField(blank=True, upload_to='website/media/distinguisted/optional/')),
                ('optional2', models.FileField(blank=True, upload_to='website/media/distinguisted/optional/')),
                ('optional3', models.FileField(blank=True, upload_to='website/media/distinguisted/optional/')),
            ],
        ),
        migrations.CreateModel(
            name='DistinguishedAlumniNominator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominator_name', models.CharField(max_length=50)),
                ('nominator_email', models.EmailField(max_length=254)),
                ('nominator_contact', models.CharField(max_length=20)),
                ('nominator_designation', models.CharField(max_length=50)),
                ('nominator_address', models.TextField()),
                ('nominator_affiliation', models.TextField()),
                ('nominator_moreinfo', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DistinguishedAlumniNominee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominee_name', models.CharField(max_length=100)),
                ('nominee_email', models.EmailField(max_length=254)),
                ('nominee_contact', models.CharField(max_length=20)),
                ('nominee_degree', models.CharField(max_length=50)),
                ('nominee_yearpass', models.IntegerField()),
                ('nominee_quals', models.TextField(blank=True, null=True)),
                ('nominee_address', models.TextField()),
                ('nominee_designation', models.CharField(max_length=50)),
                ('nominee_category', models.CharField(choices=[('AR', 'Academic Research'), ('CE', 'Corporate Development/Adminstration/Entrepreneurship'), ('SA', 'Social Sciences/Engineering and Services/Public Adminstration'), ('SS', 'Service to Society')], max_length=100)),
                ('nominee_description', models.TextField()),
                ('nominee_webpage', models.CharField(blank=True, max_length=50, null=True)),
                ('nominee_linkedin', models.CharField(blank=True, max_length=50, null=True)),
                ('nominee_awards', models.TextField(blank=True, null=True)),
                ('nominee_photo', models.ImageField(upload_to='website/media/distinguisted/images/')),
                ('nominee_resume', models.FileField(upload_to='website/media/distinguisted/resumes/')),
                ('nominee_optional1', models.FileField(blank=True, upload_to='website/media/distinguisted/optional/')),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('message', ckeditor.fields.RichTextField(default='')),
                ('include_name', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=200)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('event_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('priority', models.IntegerField(default=0)),
                ('visibility', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('file_added', models.FileField(upload_to='website/media/')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('visibility', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=200)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('publish', models.DateField()),
                ('expiry', models.DateField()),
                ('priority', models.IntegerField(default=0)),
                ('visibility', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('priority', models.IntegerField(default=0)),
                ('visibility', models.BooleanField(default=True)),
                ('external_url', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.IntegerField(default=0)),
                ('content', ckeditor.fields.RichTextField(default='')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Parent', to='website.Node')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='website/media/slider/')),
                ('visibility', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('subscription_key', models.CharField(blank=True, max_length=32, unique=True)),
                ('is_subscribed', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('contact', models.BigIntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='distinguishedalumninominator',
            name='nominee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominator', to='website.DistinguishedAlumniNominee'),
        ),
    ]
